### ISSUE TITLE
Add preview subfolder to ignore list

### ISSUE THREAD

**Issue by ValeriyKliuk** [davidsamacoits/react-native-swipeable-parallax-carousel#1]
Hi :)
It would be nice if you will add the preview subfolder to the ignore list.
![react-native-swipeable-parallax-carousel](https://user-images.githubusercontent.com/750868/28731107-8ee70e38-73a0-11e7-9443-3d0efe8d35f4.png)

Thanks

**Comment by davidsamacoits** [comment]
Done! Thank you :wink:
