### ISSUE TITLE
AutoStart + Loop

### ISSUE THREAD

**Issue by minhtamwebmaster** [davidsamacoits/react-native-swipeable-parallax-carousel#4]
Dear Mr

How to autostart + loop swiper

Thanks

**Comment by davidsamacoits** [comment]
@minhtamwebmaster Not supported currently but will definitely be part of a next release.

**Comment by danielMensah** [comment]
@minhtamwebmaster  **I've found a work around, might help**.

Start by adding a global varriable `var timer;`

Add an interval to the `constructor`:

```
    if (this.props.autoPlay) {
      timer = setInterval(() => {
        this._forceSwipe('left');
      }, this.props.playTime);
    }
```

Also need to `clearInterval` :

```
  componentWillUnmount() {
    clearInterval(timer);
  }
```

Then change `_forceSwipe()` to:

```
  _forceSwipe(direction) {
    const { autoPlay } = this.props;
    let distance = (direction === 'right') ? this.state.screenWidth : -this.state.screenWidth;
    // Calculate nextItem
    const currentitem = this.state.currentItem;
    const totalItems = this.props.data.length;
    let newitem = (direction === 'right') ? currentitem - 1 : currentitem + 1;

    if (autoPlay && newitem === totalItems) {
      distance = this.state.screenWidth * (totalItems - 1);
      newitem = 0;
    }

    this.setState({ nextItem: newitem });
    Animated.spring(this.position, {
      toValue: { x: distance, y: 0 },
    }).start(() => this._onSwipeComplete(newitem));
  }
```

And then you can add the props to the Carousel component like this:

```
<Carousel
            data={dataCarousel}
            parentScrollViewRef={this.parentScrollView}
            autoPlay={true}
            playTime={5000}
            navigationType="bars"/>
```

If you want I can try to commit it.

**Comment by minhtamwebmaster** [comment]
Yes, please commit it

2017-12-23 8:11 GMT+07:00 danielMensah <notifications@github.com>:

**Comment by danielMensah** [comment]
@minhtamwebmaster Since I have no permission to commit anything to this repo, I have created a node is module for this myself.

https://github.com/danielMensah/react-native-smart-carousel

**Comment by geminiyellow** [comment]
@davidsamacoits this repo still working?
